# Generated by Django 3.2.4 on 2021-06-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='age',
        ),
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='experience',
            field=models.IntegerField(default=5),
        ),
    ]
