# Generated by Django 3.2.4 on 2021-06-23 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50)),
                ('course_name', models.CharField(max_length=80)),
                ('lessons_total', models.IntegerField(default=30)),
                ('students_quantity', models.IntegerField(default=15)),
            ],
        ),
    ]
