# Generated by Django 3.2.4 on 2021-06-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='group',
            name='students_quantity',
        ),
        migrations.AddField(
            model_name='group',
            name='start_date',
            field=models.DateField(default='2021-06-25'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(max_length=30),
        ),
    ]
