# Generated by Django 3.2.4 on 2021-06-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20210625_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='start_date',
            field=models.DateField(default='2021-01-01'),
        ),
    ]
